export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE__SUCCESS = 'USER_UPDATE_PROFILE__SUCCESS';
export const USER_UPDATE_PROFILE__FAIL = 'USER_UPDATE_PROFILE__FAIL';
export const USER_UPDATE_PROFILE__RESET = 'USER_UPDATE_PROFILE__FAIL';


export const PASSENGER_REGISTER_REQUEST = 'PASSENGER_REGISTER_REQUEST';
export const PASSENGER_REGISTER_SUCCESS = 'PASSENGER_REGISTER_SUCCESS';
export const PASSENGER_REGISTER_FAIL = 'PASSENGER_REGISTER_FAIL';


export const DRIVER_REGISTER_REQUEST = 'DRIVER_REGISTER_REQUEST';
export const DRIVER_REGISTER_SUCCESS = 'DRIVER_REGISTER_SUCCESS';
export const DRIVER_REGISTER_FAIL = 'DRIVER_REGISTER_FAIL';